displayName: Static Response
type: middleware
iconPath: .assets/icon.png

import: github.com/jdel/staticresponse

summary: 'Static Response Middleware'

testData:
  StatusCode: 200
  Body: OK
  Headers:
    X-Test-Header: OK

