http:
  routers:
    noresponse:
      rule: PathPrefix(`/no`)
      service: noop@internal
      entryPoints:
        - web
      middlewares:
        - 444noresponse
    error:
      rule: PathPrefix(`/error`)
      service: noop@internal
      entryPoints:
        - web
      middlewares:
        - 500error
    secret:
      rule: PathPrefix(`/secret`)
      service: noop@internal
      entryPoints:
        - web
      middlewares:
        - 200+header

  middlewares:
    444noresponse:
      plugin:
        staticresponse:
          StatusCode: 444
          Body: I said no response!
    500error:
      plugin:
        staticresponse:
          StatusCode: 500
          Body: Internal Server Error
    200+header:
      plugin:
        staticresponse:
          StatusCode: 200
          Headers:
            X-Secret-Header: shhhhhh